- config_restore.go
- handler_restore.go
- internal/processors/processor_ttl.go
- io/aerospike/record_batch_writer.go
- io/aerospike/record_writer.go
> FMWK-393 Add extra-ttl flag support

- cmd/asbackup/readme.md
- cmd/internal/app/configs.go
- cmd/internal/app/configs_test.go
- cmd/internal/flags/backup.go
- cmd/internal/flags/backup_test.go
- cmd/internal/flags/common.go
- cmd/internal/flags/common_test.go
- cmd/internal/models/backup.go
- cmd/internal/models/common.go
- config_backup.go
- handler_backup_records.go
- shared.go
- tests/integration/integration_test.go
> FMWK-405 Add support for node-list option

- cmd/asbackup/readme.md
- cmd/internal/app/asbackup.go
- cmd/internal/app/asrestore.go
- cmd/internal/app/clients.go
- cmd/internal/app/clients_test.go
- cmd/internal/app/configs.go
- cmd/internal/flags/backup.go
- cmd/internal/flags/backup_test.go
- cmd/internal/models/backup.go
- added prefer racks
- fixed error with nodes and partitions backup
> FMWK-564 Add support for the prefer-racks flag

- cmd/internal/app/configs.go
- io/aws/s3/options.go
- io/aws/s3/reader.go
- io/aws/s3/writer.go
- io/azure/blob/options.go
- io/azure/blob/reader.go
- io/azure/blob/reader_writer_test.go
- io/azure/blob/writer.go
- io/gcp/storage/options.go
- io/gcp/storage/reader.go
- io/gcp/storage/reader_writer_test.go
- io/gcp/storage/writer.go
- io/local/reader.go
- for s3 WithStartAfter()
- for gcp WithStartOffset()
- for azure WithMarker()
> FMWK-559 Added read after parameter to cloud readers

- cmd/internal/app/configs.go
> APPS-1304 Add missing restore configuration mappings

- io/aws/s3/writer.go
> APPS-1323 Fix checking directory for s3

- io/aerospike/record_batch_writer.go
- added operation error processing
> APPS-1328 Add batch operation errors to log

- io/aerospike/record_batch_writer.go
- io/local/writer.go
- io/local/writer_test.go
- shared.go
- lazy folder creation
- copy send keys from write policy
> FMWK-619 Implement lazy folder creation

- cmd/asrestore/readme.md
- cmd/internal/app/asrestore.go
- cmd/internal/app/readers.go
- cmd/internal/app/readers_test.go
- cmd/internal/app/validation.go
- cmd/internal/app/validation_test.go
- cmd/internal/flags/common.go
- cmd/internal/flags/restore.go
- cmd/internal/flags/restore_test.go
- cmd/internal/models/restore.go
- io/aws/s3/options.go
- io/aws/s3/reader.go
- io/aws/s3/reader_test.go
- io/aws/s3/writer.go
- io/azure/blob/options.go
- io/azure/blob/reader.go
- io/azure/blob/reader_writer_test.go
- io/azure/blob/writer.go
- io/gcp/storage/options.go
- io/gcp/storage/reader.go
- io/gcp/storage/reader_writer_test.go
- io/gcp/storage/writer.go
- io/local/options.go
- io/local/reader.go
- io/local/reader_test.go
- io/local/writer.go
> FMWK-620 Add directory list support for restore

- cmd/asrestore/readme.md
- cmd/internal/flags/restore.go
- update documentation for -r flag on restore
> FMWK-629 Update documentation for the asrestore -r flag

- cmd/internal/app/asbackup.go
- cmd/internal/app/asrestore.go
- cmd/internal/app/readers.go
- cmd/internal/app/validation.go
- cmd/internal/models/restore.go
- io/aerospike/payload_writer.go
- io/aerospike/restore_writer.go
- io/aerospike/xdr/parser.go
- io/aerospike/xdr/record_reader.go
- io/aerospike/xdr/tcp_server.go
- io/aerospike/xdr/tcp_server_test.go
- porcessor_file_reader.go
- Fix multiply dir validation
- Filter service sets
> APPS-1471 Improve data validation

- cmd/internal/app/asbackup.go
- io/azure/blob/reader.go
- io/gcp/storage/reader.go
- fix ListObject method for azure and gcp
> APPS-1469 Fix azure ListObjects method

- internal/util/files_sort.go
- io/aws/s3/reader.go
- fix for parsing names of xdr backup
> APPS-1483 Fix file name parsing before sort

- cmd/asbackup/readme.md
- cmd/asrestore/readme.md
- cmd/internal/app/configs.go
- cmd/internal/app/configs_test.go
- cmd/internal/app/validation.go
- cmd/internal/flags/backup_xdr.go
- cmd/internal/flags/backup_xdr_test.go
- cmd/internal/flags/common.go
- cmd/internal/flags/common_test.go
> APPS-1484 Update docs for parallel-write flag

- .github/workflows/tests.yml
- cmd/internal/app/asrestore.go
- cmd/internal/app/readers.go
- cmd/internal/app/readers_test.go
- cmd/internal/app/reports.go
- config_backup_xdr.go
- handler_restore.go
- internal/asinfo/info_client_test.go
- io/aws/s3/reader.go
- io/aws/s3/reader_test.go
- io/azure/blob/reader.go
- io/azure/blob/reader_writer_test.go
- io/common/storages.go
- io/gcp/storage/reader.go
- io/gcp/storage/reader_writer_test.go
- io/local/reader.go
- io/local/reader_test.go
- io/storage/errors.go
- processor_record_writer.go
- state_test.go
- tests/integration/integration_test.go
- fixed parallelism for asbx and asb + disable-batch-writes
- fixed init of mixed restore
- fixed restore report (removed unused line)
- changed readers initializations for restore
> Fix parallelism for non bacth operations

- .github/workflows/tests.yml
- Makefile
- io/aerospike/xdr/record_reader_test.go
> Fix race condition in test

- cmd/internal/app/clients.go
- disabled log for checksum validation message
> APPS-1531 Disable S3 checksum validation skip logging

- cmd/internal/app/asbackup.go
- io/storage/aws/s3/reader.go
- io/storage/aws/s3/reader_test.go
- io/storage/aws/s3/writer.go
- io/storage/azure/blob/reader.go
- io/storage/azure/blob/reader_writer_test.go
- if xdr is disabled don't through an error on --stop-xdr command
- added strings parsing for tier and storage class
> APPS-1542 Improve Stop XDR command

- backup_restore_test.go
- handler_backup.go
- handler_restore.go
- internal/util/utils.go
- internal/util/utils_test.go
- io/encoding/asb/encode.go
- io/encoding/asb/encode_test.go
- io/encoding/asbx/decode.go
- io/encoding/asbx/encode.go
- io/encoding/asbx/encode_decode_test.go
- io_encoding.go
- mocks/Encoder_mock.go
- mocks/StreamingReader_mock.go
- porcessor_file_reader.go
- processor_file_writer.go
- token_reader.go
- token_reader_test.go
- added validation between header and file name
> Add filename validation for .ASBX

- cmd/internal/app/configs_test.go
- cmd/internal/flags/backup.go
- cmd/internal/flags/backup_test.go
- cmd/internal/flags/backup_xdr.go
- cmd/internal/flags/backup_xdr_test.go
- cmd/internal/models/backup.go
- cmd/internal/models/backup_xdr.go
- config_backup.go
- config_backup_xdr.go
- config_backup_xdr_test.go
- config_test.go
- handler_backup.go
- io/counter/writer.go
- io/lazy/writer.go
- io/lazy/writer_test.go
- io/sized/writer.go
- io/sized/writer_test.go
- processor_file_writer.go
- fix file size for compressed/encrypted files
> FMWK-690 Fix file size for compressed/encrypted files

- .github/workflows/license-checker.yaml
- internal/asinfo/info_client.go
- io/aerospike/xdr/node_reader.go
- io/aerospike/xdr/parser.go
- fix parsing keys without set name
- fix counting records
> APPS-1547 Fix record count on the namespace level

- client.go
- pipeline/pipeline.go
> FMWK-711 Fix metric counter for single mode

- cmd/internal/app/configs.go
- cmd/internal/app/configs_test.go
- config_partition_filter.go
- config_partition_filter_test.go
> FMWK-726 Make partition filter parsing function public

- .github/workflows/golangci-lint.yaml
- io/aerospike/xdr/tcp_server.go
- processor_record_writer.go
- updated linter version to 2.1.5
- fixed linter issues
> Update golangci-lint version to 2.1.5

- cmd/asbackup/readme.md
- cmd/asrestore/readme.md
- cmd/internal/config/validation.go
- cmd/internal/config/validation_test.go
- cmd/internal/flags/aws_s3.go
- cmd/internal/flags/aws_s3_test.go
- cmd/internal/flags/azure_blob.go
- cmd/internal/flags/azure_blob_test.go
- cmd/internal/flags/gcp_storage.go
- cmd/internal/flags/gcp_storage_test.go
- cmd/internal/models/aws_s3.go
- cmd/internal/models/azure_blob.go
- cmd/internal/models/gcp_storage.go
- cmd/internal/storage/clients.go
- added retry policy to each cloud storage provider's client
> FMWK-745 Add retry policy to cloud storage providers

- internal/asinfo/info_client.go
- fix rack list backup for database v 6.4
> FMWK-759 Fix rack-list backup for ASDB v6

- cmd/asrestore/main.go
- io/encoding/asb/decode.go
- io/encoding/asb/decode_test.go
- io/encoding/asb/encode.go
- io/encoding/asb/encode_test.go
> FMWK-758 Optimize ASB Decoder

- backup_restore_test.go
- cmd/internal/backup/backup.go
- cmd/internal/config/backup.go
- cmd/internal/flags/backup_xdr.go
- handler_backup.go
- handler_backup_xdr.go
- handler_restore.go
- io/storage/aws/s3/writer.go
- io/storage/azure/blob/writer.go
- io/storage/gcp/storage/writer.go
- io/storage/local/writer.go
- mocks/Writer_mock.go
- state.go
> FMWK-702 Remove state file when backup finished

- cmd/internal/logging/estimates.go
- cmd/internal/storage/readers.go
- cmd/internal/storage/writers.go
- io/storage/aws/s3/reader.go
- io/storage/azure/blob/reader.go
- io/storage/gcp/storage/reader.go
- io/storage/local/reader.go
- fix estimates for directory list.
> APPS-1748 Fix estimates calculation for restore from directory list

- pipe/chains.go
- pipe/chains_test.go
- added context check before sending to channel
> APPS-1765 Fix stopping reader chain on context cancelation

- pipe/pipe.go
- fix race condition on reading metrics from closed pipe
> APPS-1849 Fix race condition on reading metrics from closed pipeline
